// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gksxdznfdxrsjqkuzxmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdrc3hkem5mZHhyc2pxa3V6eG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NTk0MjcsImV4cCI6MjA3MjIzNTQyN30.HMsK3eoIuYNQY3TDhrHoyPqiBugH_342TfEmIMddtwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});